name: Prune container images

permissions:
    contents: read
    packages: write

on:
    workflow_dispatch:
    schedule:
        - cron: '13 9 * * *'

jobs:
    prune-container-images:
        uses: Sofie-Automation/sofie-github-workflows/.github/workflows/prune-container-images.yml@main
        with:
            dry-run: false
            prune-untagged: true
            package-name: ${{ github.event.repository.name }}
            tags-to-keep-regex: |
                ^v(\d+)
                ^develop$
                ^main$
                ^latest$
        secrets:
            prune-token: ${{ secrets.GITHUB_TOKEN }}
